### ISSUE TITLE
Migration to dssp-client 1.8: possible missing dependencies

### ISSUE THREAD

**Issue by thomaskaviani-vvvl** [e-Contract/dssp#11]
We are upgrading the version of the dssp-client from 1.7.0 to 1.8.0. 
This required us to add the following dependency according to the documentation:

<dependency>
        <groupId>be.e_contract.dssp</groupId>
        <artifactId>dssp-client-wss4j2</artifactId>
        <version>1.8.0</version>
        <scope>runtime</scope>
</dependency>

When running the application there was an issue that occured involving the instantiation of the DigitalSignatureServiceClient.

Caused by: java.lang.NoClassDefFoundError: org/apache/jcp/xml/dsig/internal/dom/XMLDSigRI
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	... 82 more

The missing class comes from a package that I tried adding as an additional dependency (not mentioned in your documentation):

package: org.apache.santuario
artifact: xmlsec

With this dependency added the Client can be instantiated, I can redirect to the e-contract page to sign a document. But when handling the signed document there still remain some issues which seem to be version mismatching.

I wonder if the xmlsec dependency had to be added in the first place, or are we missing something?

I'm happy to share additional information if needed.

**Comment by fcorneli** [comment]
> I wonder if the xmlsec dependency had to be added in the first place, or are we missing something?

This depends on the used Java EE application server.

Check out:
    https://github.com/e-Contract/dssp-example
for an example. In the `pom.xml` file you will find profiles for different application servers that we tried out ourselves.

**Comment by thomaskaviani-vvvl** [comment]
We are using a Wildfly application server and the version 1.8.0 of the dssp-client

I already added the following dependencies:

- dssp-client     (the client itself)
- dssp-client-wss4j2  (the wss4j dependency)

- jboss-javaee-all-6.0 (as stated in the pom.xml example)
- the repositories tag with the e-contract repository

When running the application we still encounter the same error:

Caused by: java.lang.NoClassDefFoundError: org/apache/jcp/xml/dsig/internal/dom/XMLDSigRI
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	... 82 more

Which again, can be solved by adding an extra dependency: 

package: org.apache.santuario
artifact: xmlsec

-> but this then gives errors when handling the signed document.

I'm pretty sure we shouldn't be adding extra dependencies to get it running. Any suggestions?

**Comment by fcorneli** [comment]
As shown within the example, for WildFly you should indeed include `dssp-client-wss4j2`.
Since WildFly already comes with WSS4J bundled, you will indeed run into classpath issues.
Hence you should refer to the WSS4J that is bundled within the WildFly application server.
Do this via:
https://github.com/e-Contract/dssp-example/blob/master/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

**Comment by thomaskaviani-vvvl** [comment]
I had indeed forgot to add this to my jboss-deployment-structure. 
However, when I sign a document on the e-contract page and get redirected back to my web-application to handle this signed document I ran into the following issue, which could indicate a version mismatch:

Caused by: java.lang.NoSuchMethodError: org.apache.wss4j.dom.message.WSSecTimestamp.<init>(Lorg/apache/wss4j/dom/message/WSSecHeader;)V
	at be.e_contract.dssp.client.wss4j2.WSSecuritySOAPHandlerWSS4J2.handleOutboundMessage(WSSecuritySOAPHandlerWSS4J2.java:196)
	at be.e_contract.dssp.client.wss4j2.WSSecuritySOAPHandlerWSS4J2.handleMessage(WSSecuritySOAPHandlerWSS4J2.java:157)
	at be.e_contract.dssp.client.wss4j2.WSSecuritySOAPHandlerWSS4J2.handleMessage(WSSecuritySOAPHandlerWSS4J2.java:64)
	at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeHandleMessage(HandlerChainInvoker.java:359)
	at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeHandlerChain(HandlerChainInvoker.java:255)
	at org.apache.cxf.jaxws.handler.HandlerChainInvoker.invokeProtocolHandlers(HandlerChainInvoker.java:132)
	at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.handleMessageInternal(SOAPHandlerInterceptor.java:169)
	at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor.access$000(SOAPHandlerInterceptor.java:71)
	at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor$1.handleMessage(SOAPHandlerInterceptor.java:81)
	at org.apache.cxf.jaxws.handler.soap.SOAPHandlerInterceptor$1.handleMessage(SOAPHandlerInterceptor.java:78)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:518)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:427)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:328)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:281)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	at com.sun.proxy.$Proxy787.pendingRequest(Unknown Source)
	at be.e_contract.dssp.client.DigitalSignatureServiceClient.downloadSignedDocument(DigitalSignatureServiceClient.java:582)

**Comment by fcorneli** [comment]
I just tried out the example application on WildFly version 21.0.0 without any problem.
Are you sure that you did not bundle WSS4J within your WAR/EAR?

**Comment by thomaskaviani-vvvl** [comment]
We tried out the example aswell on a Wildfly 11 and still got the above exception I posted.

It seems we need to further investigate our server- and networkconfiguration to pinpoint the problem.

Thanks for the assistance anyway

**Comment by fcorneli** [comment]
WildFly 11? That version is over 3 years old... do you really want to support such an old application server?

**Comment by thomaskaviani-vvvl** [comment]
Unfortunatly the choice of server and version is not up to me, this is the environment we have to work with.

**Comment by fcorneli** [comment]
WildFly 11 has WSS4J version 2.1.10, while WildFly 21 is already at 2.2.5.
You find this under `./modules/system/layers/base/org/apache/ws/security/main/`.
If you really need support for WSS4J version 2.1, you could create a `dssp-client-wss4j21` based on `dssp-client-wss4j2` and try to work-around the missing class. See `dssp-client-wss4j1` for the older way of handling WSS4J.

**Comment by thomaskaviani-vvvl** [comment]
Thanks for the tip, we will certainly try this

**Comment by fcorneli** [comment]
Since the WSS4J 2.1.x support is not really trivial, we have added support for this ourselves.
See commit: https://github.com/e-Contract/dssp/commit/a3051b8a511ad4c72b19d129478c91e0a49be9f8
Can you try out the `dssp-client-wss4j21` and let us know if it works? Then we can release 1.8.1.

Anyway, I'm not sure that -in the long run- I've helped you here as WildFly 11 is really old...
If you don't want to pay for JBoss EAP supported versions, check out the following project:
https://github.com/hasalex/eap-build

**Comment by thomaskaviani-vvvl** [comment]
We tested dssp-client-wss4j21 and it works on a Wildfly 11.

I know this version of Wildfly is really old. Migrations to 18 are planned, but not for the upcoming releases of our application.

Thank you for putting in the effort to resolve the issue, i cannot appreciate it enough.

**Comment by fcorneli** [comment]
No problem. We'll run an 1.8.1 release soon.

**Comment by fcorneli** [comment]
1.8.1 has been released.
