### ISSUE TITLE
WSSecurityException

### ISSUE THREAD

**Issue by TimDMeyer** [e-Contract/dssp#4]
I keep getting the following error when I try to download the signed document with the DigitalSignatureServiceSession:

(using version 1.2.3)

```
javax.xml.ws.soap.SOAPFaultException: org.apache.ws.security.WSSecurityException: The message has expired (WSSecurityEngine: Invalid timestamp The security semantics of the message have expired)
	at com.sun.xml.internal.ws.fault.SOAP12Fault.getProtocolException(SOAP12Fault.java:214)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:117)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:135)
	at com.sun.proxy.$Proxy187.pendingRequest(Unknown Source)
	at be.e_contract.dssp.client.DigitalSignatureServiceClient.downloadSignedDocument(DigitalSignatureServiceClient.java:470)
```

Any idea what I can do about this?

**Comment by fcorneli** [comment]
Synchronize your machine clock with NTP and try again.

**Comment by TimDMeyer** [comment]
Fixed the issue.

**Comment by fcorneli** [comment]
https://github.com/e-Contract/dssp/commit/c7603f4544b4e48c6a89a7802311ab17111d6ae7
